CREATE TABLE CLIENTE
(
  ID integer NOT NULL,
  DESCR varchar(3000) NOT NULL,
  CONSTRAINT INTEG_2 PRIMARY KEY (ID)
);

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON CLIENTE TO  SYSDBA WITH GRANT OPTION;


CREATE TABLE FACTURA
(
  NRO integer NOT NULL,
  ID integer NOT NULL,
  IMPORTE double precision NOT NULL,
  CONSTRAINT INTEG_5 PRIMARY KEY (NRO)
);

ALTER TABLE FACTURA ADD CONSTRAINT FK_CLIENTE
  FOREIGN KEY (ID) REFERENCES CLIENTE (ID);
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON FACTURA TO  SYSDBA WITH GRANT OPTION;